services:
  psql:
    hostname: "primary"
    image: postgres:latest
    container_name: transfer-db
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - POSTGRES_DB=transferdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_ROOT_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/psql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgres://postgres:postgres@psql:5432/?sslmode=disable
    depends_on:
      psql:
        condition: service_healthy
    entrypoint:
      [
        "main"
      ]
    command: [ "main" ]

volumes:
  db: